//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book_Recipe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Composition
    {
        public int ID_Recipe { get; set; }
        public int ID_Ingredient { get; set; }
        public int ID_Unit { get; set; }
        public int Number { get; set; }
        public Nullable<int> ID_Condition { get; set; }
    
        public virtual Condition Condition { get; set; }
        public virtual Ingredient Ingredient { get; set; }
        public virtual Recipe Recipe { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
