//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book_Recipe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recipe()
        {
            this.Composition = new HashSet<Composition>();
        }
    
        public int ID_Recipe { get; set; }
        public string Dish_name { get; set; }
        public Nullable<int> ID_Kitchen { get; set; }
        public int ID_Category { get; set; }
        public string Cooking_method { get; set; }
        public Nullable<int> ID_Book { get; set; }
        public Nullable<int> Calorie { get; set; }
        public Nullable<int> Portion { get; set; }
        public string Image { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Category Category { get; set; }
        public virtual Kitchen Kitchen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Composition> Composition { get; set; }
    }
}
